version: 1.0.0.{build}

environment:
  configuration: Release
  matrix:
    - node_version: "7"

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: Install-Product node $env:node_version
- cmd: |
    cd Anlab.Mvc
    appveyor-retry yarn install
    cd ..

- cmd: appveyor-retry dotnet restore
- cmd: echo %APPVEYOR_REPO_COMMIT_MESSAGE% > commit.txt 

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
- '%LOCALAPPDATA%\yarn -> **\package.json'
- anlab.mvc\node_modules -> **\package.json

before_build:
- ps: |
    $path = (Get-Item .\Anlab.Mvc\AnlabMvc.csproj).FullName
    $csproj = [xml](Get-Content $path)
    $csproj.Project.PropertyGroup.Version = $Env:APPVEYOR_BUILD_VERSION
    $csproj.Save($path)

build_script:
- cmd: msbuild .\Anlab.Mvc\AnlabMvc.csproj /t:RunWebpack /p:Configuration=%configuration%
- cmd: msbuild /t:Build /p:Configuration=%configuration%;RunOctoPack=true;PackageVersion=%APPVEYOR_BUILD_VERSION%;OctoPackReleaesNotesFile=..\commit.txt

test_script:
- cmd: vstest.console /logger:Appveyor %appveyor_build_folder%\Test\bin\%configuration%\netcoreapp1.1\Test.dll
- cmd: |
    cd Test
    dotnet test
    cd ..
- cmd: |
    cd Anlab.Mvc
    npm test
    cd ..

artifacts:
- path: '**/bin/**/AnlabMvc.*.nupkg'
  name: nugetweb

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
